// <auto-generated />
namespace MvcSampleWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class val : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(val));
        
        string IMigrationMetadata.Id
        {
            get { return "201309111600309_val"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
